import type {
  Coded,
  Industry,
  TaskFieldKey,
  TaskLevelCode,
} from "../src/modules/catalog/types.ts";

export const industries: Industry[] = [
  { code: "retail", name: "Ритейл" },
  { code: "logistics", name: "Логистика" },
  { code: "finance", name: "Финансы" },
  { code: "education", name: "Образование" },
  { code: "healthcare", name: "Здравоохранение" },
  { code: "horeca", name: "HoReCa" },
  { code: "manufacturing", name: "Производство" },
  { code: "it", name: "IT" },
  { code: "government", name: "Госсектор" },
  { code: "other", name: "Другое" },
];

export const levels: Record<TaskLevelCode, Coded<TaskLevelCode>> = {
  needs_clarification: {
    code: "needs_clarification",
    name: "Требует уточнения",
  },
  working: { code: "working", name: "Рабочая" },
  ready: { code: "ready", name: "Готовая" },
  priority: { code: "priority", name: "Приоритетная" },
};

export const statuses = {
  draft: { code: "draft", name: "Черновик" },
  published: { code: "published", name: "Опубликована" },
  in_progress: { code: "in_progress", name: "В работе" },
} as const;

export type SeedTask = {
  id: number;
  ownerBusinessId: number;
  title: string;
  companyName: string;
  industry: string;
  rating: number;
  level: TaskLevelCode;
  status: keyof typeof statuses;
  responsesCount: number;
  publishedAt: string | null;
  updatedAt: string;
  fields: Record<TaskFieldKey, string | null>;
};

const ZERNO = { ownerBusinessId: 1, companyName: "Кофейня «Зерно»" };

type Seed = Omit<SeedTask, "fields" | "updatedAt"> & {
  updatedAt?: string;
  fields: Partial<Record<TaskFieldKey, string | null>> &
    Pick<Record<TaskFieldKey, string>, "context" | "need">;
};

const seed = (task: Seed): SeedTask => ({
  ...task,
  updatedAt: task.updatedAt ?? task.publishedAt ?? "2026-09-22T08:30:00Z",
  fields: {
    targetUsers: null,
    dataMaterials: null,
    constraints: null,
    expectedResult: null,
    successCriteria: null,
    contact: null,
    interactionFormat: null,
    ...task.fields,
  },
});

export const seededTasks = (): SeedTask[] =>
  [
    seed({
      id: 12,
      ...ZERNO,
      title: "Прогноз спроса на выпечку",
      industry: "horeca",
      rating: 78,
      level: "ready",
      status: "published",
      responsesCount: 3,
      publishedAt: "2026-09-20T10:00:00Z",
      fields: {
        context: "Сеть из 4 кофеен в Астане, выпечку готовим сами каждое утро.",
        need: "Каждый день списываем до 15% выпечки. Нужна модель, которая по продажам прошлых недель подскажет, сколько печь на завтра.",
        targetUsers: "Администраторы кофеен, которые утром заказывают выпечку.",
        dataMaterials: "Выгрузка продаж по позициям за 12 месяцев в CSV.",
        constraints: "Срок — 6 недель. Решение работает в браузере.",
        expectedResult:
          "Веб-страница с прогнозом на завтра по каждой позиции и кофейне.",
        successCriteria: "Списания снижаются до 8% за месяц пилота.",
        contact: "Айгерим Нурланова, +77011234567",
        interactionFormat: null,
      },
    }),
    seed({
      id: 15,
      ...ZERNO,
      title: "Чат-бот для записи к врачу",
      industry: "healthcare",
      rating: 0,
      level: "needs_clarification",
      status: "draft",
      responsesCount: 0,
      publishedAt: null,
      updatedAt: "2026-09-22T08:30:00Z",
      fields: {
        context: "Черновик: идея для партнёрской клиники по соседству.",
        need: "Пациенты звонят в регистратуру, линия постоянно занята. Хотим бота в мессенджере для записи.",
        contact: "Айгерим Нурланова, +77011234567",
      },
    }),
    seed({
      id: 21,
      ...ZERNO,
      title: "Программа лояльности без пластиковых карт",
      industry: "horeca",
      rating: 64,
      level: "working",
      status: "in_progress",
      responsesCount: 5,
      publishedAt: "2026-09-05T09:00:00Z",
      fields: {
        context: "Гости копят штампы на бумажных карточках и часто их теряют.",
        need: "Нужна простая электронная карта лояльности по номеру телефона, которую бариста отмечает за секунду.",
        targetUsers: "Бариста и постоянные гости.",
        constraints: "Без отдельного приложения для гостя.",
        contact: "Айгерим Нурланова, +77011234567",
        interactionFormat: "Созвон раз в неделю, чат в Telegram.",
      },
    }),
    seed({
      id: 1,
      ownerBusinessId: 101,
      companyName: "Магнум Экспресс",
      title: "Оптимизация выкладки на полках",
      industry: "retail",
      rating: 93,
      level: "priority",
      status: "published",
      responsesCount: 11,
      publishedAt: "2026-09-18T07:30:00Z",
      fields: {
        context: "120 магазинов у дома, планограммы обновляются вручную.",
        need: "Нужно по чекам определить, какие товары стоит ставить рядом, и автоматически предлагать планограмму для каждого магазина.",
        targetUsers: "Категорийные менеджеры.",
        dataMaterials: "Обезличенные чеки за 6 месяцев, справочник товаров.",
        constraints: "Данные не покидают внутренний контур компании.",
        expectedResult: "Отчёт с рекомендациями и прототип планограммы.",
        successCriteria: "Рост среднего чека на 3% в пилотных магазинах.",
        contact: "Данияр Касымов, d.kasymov@magnum.example",
        interactionFormat: "Очные встречи в офисе раз в две недели.",
      },
    }),
    seed({
      id: 2,
      ownerBusinessId: 102,
      companyName: "ТрансЛогистик",
      title: "Маршрутизация курьеров по городу",
      industry: "logistics",
      rating: 88,
      level: "ready",
      status: "published",
      responsesCount: 7,
      publishedAt: "2026-09-16T11:00:00Z",
      fields: {
        context: "40 курьеров доставляют заказы по Алматы.",
        need: "Диспетчер строит маршруты вручную, курьеры теряют до часа в пробках. Нужен сервис автоматического построения маршрутов.",
        targetUsers: "Диспетчеры и курьеры.",
        dataMaterials: "История заказов с адресами за 3 месяца.",
        constraints: "Интеграция с 2ГИС API.",
        expectedResult: "Веб-панель диспетчера с маршрутами на день.",
        successCriteria: "Среднее время доставки сокращается на 15%.",
        contact: "Олжас Серикбаев, +77051112233",
      },
    }),
    seed({
      id: 3,
      ownerBusinessId: 103,
      companyName: "Банк «Сарыарка»",
      title: "Классификатор обращений клиентов",
      industry: "finance",
      rating: 91,
      level: "priority",
      status: "in_progress",
      responsesCount: 14,
      publishedAt: "2026-09-02T06:00:00Z",
      fields: {
        context: "Контакт-центр получает 3000 письменных обращений в день.",
        need: "Операторы вручную сортируют обращения по темам. Нужна модель, которая определяет тему и срочность обращения.",
        targetUsers: "Операторы контакт-центра.",
        dataMaterials: "20 000 размеченных обращений.",
        constraints: "Модель должна работать без внешних API.",
        expectedResult: "Сервис с REST API и отчётом о качестве.",
        successCriteria: "Точность классификации не ниже 85%.",
        contact: "Мадина Ержанова, m.erzhanova@saryarka.example",
        interactionFormat: "Еженедельные демо, общий канал в Slack.",
      },
    }),
    seed({
      id: 4,
      ownerBusinessId: 104,
      companyName: "Школа «Болашак»",
      title: "Электронный дневник для родителей",
      industry: "education",
      rating: 55,
      level: "working",
      status: "published",
      responsesCount: 2,
      publishedAt: "2026-09-12T08:00:00Z",
      fields: {
        context: "Частная школа, 600 учеников.",
        need: "Родители узнают об оценках только на собраниях. Нужен простой дневник с уведомлениями.",
        targetUsers: "Родители и классные руководители.",
        contact: "Гульнара Ахметова, +77019998877",
      },
    }),
    seed({
      id: 5,
      ownerBusinessId: 105,
      companyName: "Клиника «Шипагер»",
      title: "Напоминания пациентам о приёме",
      industry: "healthcare",
      rating: 72,
      level: "ready",
      status: "published",
      responsesCount: 4,
      publishedAt: "2026-09-14T09:30:00Z",
      fields: {
        context: "Каждый пятый пациент не приходит на запись.",
        need: "Нужны автоматические напоминания в WhatsApp за сутки и за два часа до приёма с возможностью отменить запись.",
        targetUsers: "Пациенты и администраторы клиники.",
        dataMaterials: "Расписание врачей в Google Sheets.",
        constraints: "Соблюдение закона о персональных данных.",
        expectedResult: "Работающая интеграция и панель администратора.",
        successCriteria: "Неявки снижаются вдвое.",
        contact: "Ерлан Тулегенов, +77077776655",
      },
    }),
    seed({
      id: 6,
      ownerBusinessId: 106,
      companyName: "Ресторан «Дастархан»",
      title: "Меню с QR-кодом и заказом со стола",
      industry: "horeca",
      rating: 34,
      level: "needs_clarification",
      status: "published",
      responsesCount: 1,
      publishedAt: "2026-09-21T15:00:00Z",
      fields: {
        context: "Ресторан на 80 посадочных мест.",
        need: "Хотим, чтобы гости могли заказывать со стола. Пока не решили, нужна ли оплата онлайн.",
        contact: "Асель Жумабаева, +77024443322",
      },
    }),
    seed({
      id: 7,
      ownerBusinessId: 107,
      companyName: "КазМеталл",
      title: "Учёт простоев оборудования",
      industry: "manufacturing",
      rating: 81,
      level: "ready",
      status: "published",
      responsesCount: 6,
      publishedAt: "2026-09-10T05:00:00Z",
      fields: {
        context: "Цех на 30 станков, простои фиксируются в бумажном журнале.",
        need: "Нужно планшетное приложение, где мастер отмечает причину простоя, и отчёт по потерям за смену.",
        targetUsers: "Мастера смен и главный инженер.",
        dataMaterials: "Сканы журналов за полгода.",
        constraints: "Работа без интернета с последующей синхронизацией.",
        expectedResult: "PWA и дашборд.",
        successCriteria: "Все простои фиксируются в течение 5 минут.",
        contact: "Бауыржан Омаров, +77015556644",
        interactionFormat: "Выезд на производство в начале проекта.",
      },
    }),
    seed({
      id: 8,
      ownerBusinessId: 108,
      companyName: "SoftDev KZ",
      title: "Автотесты для внутреннего API",
      industry: "it",
      rating: 67,
      level: "working",
      status: "published",
      responsesCount: 9,
      publishedAt: "2026-09-19T12:00:00Z",
      fields: {
        context: "Команда из 8 разработчиков, тестов почти нет.",
        need: "Нужен набор автотестов для ключевых сценариев API и запуск в CI.",
        targetUsers: "Разработчики.",
        dataMaterials: "OpenAPI-спецификация.",
        contact: "Тимур Ли, t.li@softdev.example",
      },
    }),
    seed({
      id: 9,
      ownerBusinessId: 109,
      companyName: "Акимат района",
      title: "Карта обращений жителей",
      industry: "government",
      rating: 58,
      level: "working",
      status: "published",
      responsesCount: 3,
      publishedAt: "2026-09-08T04:00:00Z",
      fields: {
        context: "Жители жалуются на ямы и освещение через разные каналы.",
        need: "Нужна публичная карта, где видно обращения и их статус.",
        targetUsers: "Жители района и сотрудники акимата.",
        constraints: "Хостинг только на серверах в Казахстане.",
        contact: "Приёмная акимата, +77172000000",
      },
    }),
    seed({
      id: 10,
      ownerBusinessId: 110,
      companyName: "Фонд «Мейірім»",
      title: "Учёт волонтёров и смен",
      industry: "other",
      rating: 29,
      level: "needs_clarification",
      status: "published",
      responsesCount: 0,
      publishedAt: "2026-09-22T10:00:00Z",
      fields: {
        context: "Фонд помогает пожилым людям, 150 волонтёров.",
        need: "Смены распределяются в чатах, кто-то приходит дважды, кто-то не приходит вовсе.",
        contact: "Жанар Нургалиева, +77473332211",
      },
    }),
    seed({
      id: 11,
      ownerBusinessId: 111,
      companyName: "Small Mart",
      title: "Прогноз остатков для закупок",
      industry: "retail",
      rating: 75,
      level: "ready",
      status: "published",
      responsesCount: 5,
      publishedAt: "2026-09-15T08:00:00Z",
      fields: {
        context: "Сеть из 12 минимаркетов.",
        need: "Закупщики заказывают товар на глаз, часть позиций заканчивается к выходным. Нужен прогноз остатков на неделю.",
        targetUsers: "Закупщики.",
        dataMaterials: "Продажи и поставки за год.",
        expectedResult: "Таблица рекомендуемых заказов.",
        successCriteria: "Дефицит популярных позиций сокращается на 30%.",
        contact: "Руслан Абенов, +77012223344",
      },
    }),
    seed({
      id: 13,
      ownerBusinessId: 112,
      companyName: "Kaspi-партнёр «Техно»",
      title: "Аналитика отзывов покупателей",
      industry: "retail",
      rating: 46,
      level: "working",
      status: "published",
      responsesCount: 2,
      publishedAt: "2026-09-11T13:00:00Z",
      fields: {
        context: "Интернет-магазин электроники, 5000 отзывов в месяц.",
        need: "Хотим понимать, на что чаще всего жалуются покупатели, без ручного чтения отзывов.",
        dataMaterials: "Выгрузка отзывов в JSON.",
        contact: "Алина Ким, a.kim@techno.example",
      },
    }),
    seed({
      id: 14,
      ownerBusinessId: 113,
      companyName: "Складской комплекс «Орда»",
      title: "Сканирование паллет по фото",
      industry: "logistics",
      rating: 95,
      level: "priority",
      status: "published",
      responsesCount: 12,
      publishedAt: "2026-09-17T06:30:00Z",
      fields: {
        context: "Склад на 20 000 паллетомест, инвентаризация занимает неделю.",
        need: "Нужно приложение, которое по фотографии стеллажа считает паллеты и сверяет их с учётной системой.",
        targetUsers: "Кладовщики.",
        dataMaterials: "2000 размеченных фотографий стеллажей.",
        constraints: "Работа на Android-смартфонах среднего класса.",
        expectedResult: "Мобильное приложение и отчёт о расхождениях.",
        successCriteria: "Инвентаризация проходит за 2 дня.",
        contact: "Серик Мухамедов, +77056667788",
        interactionFormat: "Тестирование на складе по пятницам.",
      },
    }),
    seed({
      id: 16,
      ownerBusinessId: 114,
      companyName: "Микрофинанс «Капитал»",
      title: "Скоринг заявок малого бизнеса",
      industry: "finance",
      rating: 69,
      level: "working",
      status: "published",
      responsesCount: 8,
      publishedAt: "2026-09-09T07:00:00Z",
      fields: {
        context: "Выдаём микрокредиты ИП, решение принимает кредитный эксперт.",
        need: "Нужна модель предварительной оценки заявки, которая подсвечивает риски для эксперта.",
        dataMaterials: "Обезличенные заявки и история погашений.",
        constraints: "Решение должно быть объяснимым.",
        contact: "Азамат Жаксыбеков, +77018889900",
      },
    }),
    seed({
      id: 17,
      ownerBusinessId: 115,
      companyName: "Колледж цифровых технологий",
      title: "Тренажёр для подготовки к экзаменам",
      industry: "education",
      rating: 84,
      level: "ready",
      status: "published",
      responsesCount: 10,
      publishedAt: "2026-09-13T10:00:00Z",
      fields: {
        context: "Студенты готовятся к экзаменам по бумажным сборникам.",
        need: "Нужен веб-тренажёр с банком вопросов, случайными вариантами и статистикой ошибок.",
        targetUsers: "Студенты и преподаватели.",
        dataMaterials: "Банк из 1500 вопросов в Word.",
        expectedResult: "Веб-приложение с кабинетом преподавателя.",
        successCriteria: "Средний балл на экзамене растёт на 10%.",
        contact: "Айжан Сатпаева, +77014445566",
        interactionFormat: "Онлайн-встречи по средам.",
      },
    }),
    seed({
      id: 18,
      ownerBusinessId: 116,
      companyName: "Аптека «Дәрі»",
      title: "Поиск аналогов лекарств",
      industry: "healthcare",
      rating: 38,
      level: "needs_clarification",
      status: "published",
      responsesCount: 1,
      publishedAt: "2026-09-19T08:00:00Z",
      fields: {
        context: "Сеть из 9 аптек.",
        need: "Фармацевтам нужен быстрый поиск аналогов по действующему веществу.",
        contact: "Мария Ким, +77001234567",
      },
    }),
    seed({
      id: 19,
      ownerBusinessId: 117,
      companyName: "Кондитерская «Бал»",
      title: "Онлайн-конструктор тортов",
      industry: "horeca",
      rating: 52,
      level: "working",
      status: "published",
      responsesCount: 4,
      publishedAt: "2026-09-07T11:00:00Z",
      fields: {
        context: "Принимаем заказы на торты по телефону и в Instagram.",
        need: "Клиенты долго согласовывают начинку и оформление. Нужен конструктор с расчётом цены.",
        targetUsers: "Клиенты кондитерской.",
        contact: "Дина Сулейменова, +77087654321",
      },
    }),
    seed({
      id: 20,
      ownerBusinessId: 118,
      companyName: "АгроПром",
      title: "Мониторинг температуры в теплицах",
      industry: "manufacturing",
      rating: 61,
      level: "working",
      status: "published",
      responsesCount: 3,
      publishedAt: "2026-09-06T05:00:00Z",
      fields: {
        context: "6 теплиц, датчики уже установлены.",
        need: "Нужны оповещения агроному при выходе температуры и влажности за допустимые пределы.",
        dataMaterials: "Доступ к MQTT-брокеру датчиков.",
        contact: "Нурлан Искаков, +77023334455",
      },
    }),
    seed({
      id: 22,
      ownerBusinessId: 119,
      companyName: "CloudOps Studio",
      title: "Дашборд затрат на облако",
      industry: "it",
      rating: 86,
      level: "ready",
      status: "published",
      responsesCount: 6,
      publishedAt: "2026-09-20T14:00:00Z",
      fields: {
        context: "Используем три облачных провайдера.",
        need: "Счета приходят раздельно, никто не видит общую картину. Нужен единый дашборд затрат по проектам.",
        targetUsers: "Технический директор и руководители проектов.",
        dataMaterials: "Выгрузки биллинга в CSV.",
        expectedResult: "Дашборд с разбивкой по проектам и месяцам.",
        successCriteria: "Затраты видны не позднее следующего дня.",
        contact: "Ильяс Маратов, i.maratov@cloudops.example",
      },
    }),
    seed({
      id: 23,
      ownerBusinessId: 120,
      companyName: "ЦОН района",
      title: "Электронная очередь с прогнозом ожидания",
      industry: "government",
      rating: 90,
      level: "priority",
      status: "published",
      responsesCount: 9,
      publishedAt: "2026-09-04T04:00:00Z",
      fields: {
        context: "В часы пик ожидание в ЦОНе превышает час.",
        need: "Нужна электронная очередь, показывающая прогноз ожидания на сайте, чтобы люди приходили в удобное время.",
        targetUsers: "Посетители ЦОНа.",
        dataMaterials: "Журнал талонов за год.",
        constraints: "Интеграция с существующим терминалом талонов.",
        expectedResult: "Виджет на сайте и табло в зале.",
        successCriteria: "Пиковое ожидание снижается до 30 минут.",
        contact: "Отдел цифровизации, +77172111111",
        interactionFormat: "Согласование через официальные письма.",
      },
    }),
    seed({
      id: 24,
      ownerBusinessId: 121,
      companyName: "Логистика Плюс",
      title: "Трекинг грузов для клиентов",
      industry: "logistics",
      rating: 42,
      level: "working",
      status: "published",
      responsesCount: 2,
      publishedAt: "2026-09-03T09:00:00Z",
      fields: {
        context: "Клиенты звонят менеджерам, чтобы узнать, где груз.",
        need: "Нужна страница отслеживания груза по номеру накладной.",
        contact: "Арман Бектуров, +77076665544",
      },
    }),
    seed({
      id: 25,
      ownerBusinessId: 122,
      companyName: "Страховая «Сенім»",
      title: "Распознавание документов для выплат",
      industry: "finance",
      rating: 31,
      level: "needs_clarification",
      status: "published",
      responsesCount: 0,
      publishedAt: "2026-09-01T06:00:00Z",
      fields: {
        context: "Клиенты присылают фото документов для страховых выплат.",
        need: "Сотрудники перепечатывают данные вручную. Хотим автоматизировать, но формат пока не определён.",
        contact: "Ляззат Оспанова, +77071230000",
      },
    }),
    seed({
      id: 26,
      ownerBusinessId: 123,
      companyName: "Типография «Кітап»",
      title: "Калькулятор стоимости тиража",
      industry: "other",
      rating: 73,
      level: "ready",
      status: "published",
      responsesCount: 4,
      publishedAt: "2026-09-18T12:00:00Z",
      fields: {
        context: "Менеджеры считают стоимость заказа в Excel по 20 параметрам.",
        need: "Нужен онлайн-калькулятор для клиентов с мгновенным расчётом стоимости и сроков.",
        targetUsers: "Клиенты типографии и менеджеры.",
        dataMaterials: "Excel-файл с формулами.",
        expectedResult: "Калькулятор на сайте.",
        successCriteria: "Половина заказов оформляется без звонка менеджеру.",
        contact: "Ержан Абдрахманов, +77029990011",
      },
    }),
  ].sort((a, b) => a.id - b.id);
